spring.application.name=hrms
server.port=8080

spring.datasource.url=jdbc:postgresql://db.uxvsqjektsssfvsfprtd.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=L8Q2SZnVdnZCPpAM
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Load .env file
spring.config.import=optional:file:.env[.properties]
